[package]
name = "termshare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
dialoguer = "0.10.0"